language: objective-c
osx_image: xcode8.2

defore_script:
  - fastlane snapshot reset_simulators --force

script:
  - set -o pipefail && xcodebuild test -workspace Travis-Test.xcworkspace -scheme Travis-Test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.2' | xcpretty -c
